version: '2'

services:
  nextcloud:
    container_name: ${DOCKER_CONTAINER_NAME}
    image: nextcloud:latest
    restart: always
    ports:
      - ${DOCKER_PORT}:80
    volumes:
      - ./files:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - REDIS_HOST=${DOCKER_CONTAINER_NAME}_redist
  redis:
    container_name: ${DOCKER_CONTAINER_NAME}_redist 
    expose:
      - 6379
    image: redis:alpine
    restart: always

networks:
  default:
    external:
      name: "docker-lan"
